### ISSUE TITLE
Raijin: Not working with Python 2.7.3

### ISSUE THREAD

**Issue by ScottWales** [coecms/ARCCSSive#14]
RT # 88305 - ARCCSSive not working with default Python

**Comment by ScottWales** [comment]
```
saw562@raijin1 ~ $ module purge
saw562@raijin1 ~ $ module load python/2.7.3
saw562@raijin1 ~ $ module load pythonlib/ARCCSSive
saw562@raijin1 ~ $ python -c 'import ARCCSSive'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/projects/access/apps/pythonlib/ARCCSSive/0.2.0/lib/python2.7/site-packages/ARCCSSive/__init__.py", line 1, in <module>
    from .pkg_info import __version__
  File "/projects/access/apps/pythonlib/ARCCSSive/0.2.0/lib/python2.7/site-packages/ARCCSSive/pkg_info.py", line 20, in <module>
    __version__ = pkg_resources.get_distribution(__name__).version
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 311, in get_distribution
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 197, in get_provider
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 666, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 565, in resolve
pkg_resources.DistributionNotFound: ARCCSSive
```
vs.
```
saw562@raijin3 ~ $ module purge
saw562@raijin3 ~ $ module load python/2.7.5
saw562@raijin3 ~ $ module load pythonlib/ARCCSSive
saw562@raijin3 ~ $ python -c 'import ARCCSSive'
```

**Comment by ScottWales** [comment]
There appears to be a problem with `pkg_resources` in NCI's Python 2.7.3:

    # 2.7.3
    python -c 'import pkg_resources; print list(pkg_resources.Environment())'
    ['sqlalchemy', 'pyproj', 'python', 'wsgiref', 'matplotlib', 'markupsafe', 'scipy', 'nose', 'setuptools', 'ipython', 'esgf-pyclient', 'numpy', 'gdal']

    # 2.7.5
    python -c 'import pkg_resources; print list(pkg_resources.Environment())'
    ['sqlalchemy', 'funcsigs', 'pbr', 'python', 'numpy', 'six', 'wsgiref', 'matplotlib', 'markupsafe', 'scipy', 'jinja2', 'mock', 'setuptools', 'sympy', 'arccssive', 'esgf-pyclient', 'ipython', 'gdal', 'nose']

Updating setuptools doesn't improve things - may be best to disable version information for 2.7.3
